New component about me and fix border styles
igor-napierala-wttech/awesome-website pull request #7
Opened 2022-03-16 12:53 UTC by dmytro-slobodian-wttech

merge border and border color
new component About Me

2022-03-16 13:09 UTC, thisisui requested changes

2022-03-16 13:09 UTC, thisisui commented on src/components/SearchBlock.vue
> +  border: 0px;
0 should be without 'px'

2022-03-16 13:09 UTC, thisisui commented on src/components/SearchBlock.vue
> +  padding-right: 0px;
0 without unit please

2022-03-18 10:07 UTC, igor-napierala-wttech commented on src/components/Postblock.vue
> +      class="top_image_post_block_Img_main"
Img should be img

2022-03-18 10:07 UTC, igor-napierala-wttech commented on src/components/Postblock.vue
> +  margin-top: 20px;
you can mix 3 lines in one 

`margin: 20px auto inherit;`

probably it was initial or inherit - please check in docs https://developer.mozilla.org/pl/docs/Web/CSS/Margin

2022-03-18 10:07 UTC, igor-napierala-wttech commented on src/components/Postblock.vue
> +  margin-top: 20px;
merge 3 lines into one - margin ones

2022-03-18 10:07 UTC, igor-napierala-wttech commented on src/components/Postblock.vue
> +  margin-top: 20px;
merge 3 lines into one - margin ones

2022-03-21 11:46 UTC, merged